#! /bin/sh
### BEGIN INIT INFO
# Provides:       TLON-Adhoc
# Required-Start: $all
# Required-Stop:
# Default-Start: 	2 3 4 5
# Default-Stop:	0 1 6
# Short-Description: Ejecuta /home/pi/carpeta/Tesis/creacionred/CreateAdhoc.sh si existe
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start() {
        if [ -x /home/pi/carpeta/Tesis/creacionred/CreateAdhoc.sh ]; then
                [ "$VERBOSE" != no ] && log_begin_msg "Inicio de nodo Ad-hoc"
                /home/pi/carpeta/Tesis/creacionred/CreateAdhoc.sh
                ES=$?
                [ "$VERBOSE" != no ] && log_end_msg $ES
                return $ES
        fi
}

case "$1" in
    start)
        do_start
        ;;
    restart|reload|force-reload)
        echo "Error: argumento '$1' no valido" >&2
        exit 3
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac

